# Generated by Django 4.2.5 on 2023-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_email_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/product_cover/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='comment text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='product  creation time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='product  modified time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='product title'),
        ),
    ]
