# Generated by Django 4.2.5 on 2023-09-17 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_comment_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='product  creation time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='product  modified time'),
        ),
    ]
